<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>[Pigstep] Farm Summary Report</title>
</head>
<body style="margin:0; padding:0; background:#f3f6fb; font-family:Arial, sans-serif; color:#172033;">
    <div style="max-width:680px; margin:0 auto; padding:32px 16px;">
        <div style="background:#ffffff; border:1px solid #e2e8f0; border-radius:16px; overflow:hidden;">
            <div style="background:#0f172a; color:#ffffff; padding:22px 24px;">
                <h1 style="margin:0; font-size:22px;">Pigstep Farm Summary Report</h1>
                <p style="margin:8px 0 0; color:#cbd5e1; line-height:1.5;">
                    Manual farm summary report generated by Pigstep.
                </p>
            </div>

            <div style="padding:24px;">
                <p style="margin:0 0 14px; line-height:1.6; color:#334155;">
                    A current farm summary report was generated on
                    <strong>{{ $summary['generated_at']->format('Y-m-d H:i:s') }}</strong>.
                    The PDF and CSV versions are attached to this email.
                </p>

                <table style="width:100%; border-collapse:collapse; margin:18px 0;">
                    <tbody>
                        <tr>
                            <td style="padding:10px; border:1px solid #e2e8f0; background:#f8fafc; font-weight:700;">Active pigs</td>
                            <td style="padding:10px; border:1px solid #e2e8f0;">{{ number_format((int) $metrics['active_pigs']) }}</td>
                        </tr>
                        <tr>
                            <td style="padding:10px; border:1px solid #e2e8f0; background:#f8fafc; font-weight:700;">Net position</td>
                            <td style="padding:10px; border:1px solid #e2e8f0;">PHP {{ number_format((float) $metrics['net_position'], 2) }}</td>
                        </tr>
                        <tr>
                            <td style="padding:10px; border:1px solid #e2e8f0; background:#f8fafc; font-weight:700;">Protocol overdue</td>
                            <td style="padding:10px; border:1px solid #e2e8f0;">{{ number_format((int) $metrics['protocol_overdue']) }}</td>
                        </tr>
                        <tr>
                            <td style="padding:10px; border:1px solid #e2e8f0; background:#f8fafc; font-weight:700;">Protocol due today</td>
                            <td style="padding:10px; border:1px solid #e2e8f0;">{{ number_format((int) $metrics['protocol_due_today']) }}</td>
                        </tr>
                    </tbody>
                </table>

                <p style="margin:0; line-height:1.6; color:#334155;">
                    Attachments included:
                    <strong>Farm Summary PDF</strong> and <strong>Farm Summary CSV</strong>.
                </p>
            </div>

            <div style="padding:16px 24px; background:#f8fafc; border-top:1px solid #e2e8f0; color:#64748b; font-size:12px; line-height:1.6;">
                Generated by Pigstep. Product by Kirjane Labs.<br>
                Lead Developer: Kirch Ivan A. Balite. Co-Developer: Osiris Kedigadash Palac.<br>
                Support: kirchivan123@gmail.com / 09486328353.<br>
                © {{ date('Y') }} Kirjane Labs. All rights reserved.
            </div>
        </div>
    </div>
</body>
</html>
